name: Publish Common Library

on:
  push:
    tags:
      - 'v*.*.*' # Example v1.0.0
    workflow_dispatch:  # Allows you to run this manually

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.GITHUB_USERNAME }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build and test before publishing
        run: ./gradlew build test --no-daemon

      - name: Publish to GitHub Packages
        run: ./gradlew publish --no-daemon
